workflows:
  build_flutter_apk:
    name: Build Flutter debug APK
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Create android folder if missing
        script: |
          if [ ! -d "android" ]; then
            flutter create .
          fi
      - name: Flutter clean & pub get
        script: |
          flutter clean
          flutter pub get
      - name: Stop gradle daemons (safety)
        script: |
          (cd android && ./gradlew --stop || true)
      - name: Build debug APK (no-daemon + stacktrace)
        script: |
          (cd android && ./gradlew assembleDebug --no-daemon --stacktrace --info)
    artifacts:
      - android/app/build/outputs/**/*.apk
