workflows:
  build_flutter_apk:
    name: Build Flutter debug APK
    max_build_duration: 60
    environment:
      flutter: stable

    scripts:
      - name: Go to project root
        script: |
          cd $CM_BUILD_DIR
          echo "PWD: $PWD"
          ls -la

      - name: Ensure full Android structure (recreate if incomplete)
        script: |
          set -e
          NEED_RECREATE=0
          if [ ! -d "android" ]; then
            NEED_RECREATE=1
          elif [ ! -f "android/app/src/main/AndroidManifest.xml" ]; then
            NEED_RECREATE=1
          fi
          if [ "$NEED_RECREATE" = "1" ]; then
            echo ">> Recreating android/"
            rm -rf android
            flutter create .
          else
            echo ">> android/ looks OK"
          fi

      - name: Clean and get dependencies
        script: |
          flutter clean
          flutter pub get

      - name: Build debug APK
        script: |
          # Add flutterEmbedding=2 meta-data if missing (safe/idempotent)
          if ! grep -q 'flutterEmbedding' android/app/src/main/AndroidManifest.xml; then
            awk '1; /<\/application>/ && !x {print "    <meta-data android:name=\"flutterEmbedding\" android:value=\"2\" />"; x=1}' \
              android/app/src/main/AndroidManifest.xml > /tmp/AndroidManifest.xml \
              && mv /tmp/AndroidManifest.xml android/app/src/main/AndroidManifest.xml
          fi

          # Info: ensure MainActivity exists at the expected path
          test -f android/app/src/main/kotlin/com/ezanvakti/plus/MainActivity.kt && echo "MainActivity.kt bulundu."

          flutter build apk --debug

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
