workflows:
  build_flutter_apk:
    name: Build Flutter debug APK
    max_build_duration: 60
    environment:
      flutter: stable

    scripts:
      - name: Go to Flutter project folder
        script: |
          cd $CM_BUILD_DIR/ezan_vakti_plus_repo
          echo ">>> Current directory:"
          pwd
          echo ">>> Files here:"
          ls -l

      - name: Create android folder if missing
        script: |
          if [ ! -d "android" ]; then
            flutter create .
          fi

      - name: Clean and get dependencies
        script: |
          flutter clean
          flutter pub get

      - name: Build debug APK
        script: |
          flutter build apk --debug

    artifacts:
      - ezan_vakti_plus_repo/build/app/outputs/flutter-apk/*.apk
