workflows:
  build_flutter_apk:
    name: Build Flutter debug APK
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Check and create android folder
        script: |
          echo ">>> Checking android folder..."
          if [ ! -d "android" ]; then
            echo ">>> Android folder not found, creating..."
            flutter create .
          else
            echo ">>> Android folder already exists."
          fi
      - name: Get dependencies
        script: flutter pub get
      - name: Build debug APK
        script: flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
