workflows:
  build_flutter_apk:
    name: Build Flutter debug APK
    max_build_duration: 60
    environment:
      flutter: stable

    scripts:
      - name: Move to project root
        script: |
          cd $CM_BUILD_DIR
          echo ">>> Current directory:"
          pwd
          echo ">>> Files here:"
          ls -l

      - name: Check and create android folder if missing
        script: |
          if [ ! -d "android" ]; then
            echo ">>> Android folder not found, creating..."
            flutter create .
          else
            echo ">>> Android folder exists."
          fi

      - name: Flutter clean & get dependencies
        script: |
          flutter clean
          flutter pub get

      - name: Build debug APK
        script: |
          flutter build apk --debug

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
