workflows:
  build_flutter_apk:
    name: Build Flutter debug APK
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: (Opsiyonel) android yoksa oluştur
        script: |
          if [ ! -d "android" ]; then
            flutter create .
          fi
      - name: Bağımlılıkları indir
        script: flutter pub get
      - name: Debug APK derle
        script: flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
